/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.intuit.craft.streaming.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Message_dims extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2677908004546357566L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Message_dims\",\"namespace\":\"Signup\",\"fields\":[{\"name\":\"channel\",\"type\":\"string\",\"doc\":\"Channel from where the event has been generated.\"},{\"name\":\"item\",\"type\":\"string\",\"doc\":\"The Intuit item for which the event has been generated.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Channel from where the event has been generated. */
  @Deprecated public java.lang.CharSequence channel;
  /** The Intuit item for which the event has been generated. */
  @Deprecated public java.lang.CharSequence item;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Message_dims() {}

  /**
   * All-args constructor.
   * @param channel Channel from where the event has been generated.
   * @param item The Intuit item for which the event has been generated.
   */
  public Message_dims(java.lang.CharSequence channel, java.lang.CharSequence item) {
    this.channel = channel;
    this.item = item;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return channel;
    case 1: return item;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: channel = (java.lang.CharSequence)value$; break;
    case 1: item = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'channel' field.
   * @return Channel from where the event has been generated.
   */
  public java.lang.CharSequence getChannel() {
    return channel;
  }

  /**
   * Sets the value of the 'channel' field.
   * Channel from where the event has been generated.
   * @param value the value to set.
   */
  public void setChannel(java.lang.CharSequence value) {
    this.channel = value;
  }

  /**
   * Gets the value of the 'item' field.
   * @return The Intuit item for which the event has been generated.
   */
  public java.lang.CharSequence getItem() {
    return item;
  }

  /**
   * Sets the value of the 'item' field.
   * The Intuit item for which the event has been generated.
   * @param value the value to set.
   */
  public void setItem(java.lang.CharSequence value) {
    this.item = value;
  }

  /**
   * Creates a new Message_dims RecordBuilder.
   * @return A new Message_dims RecordBuilder
   */
  public static com.intuit.craft.streaming.avro.Message_dims.Builder newBuilder() {
    return new com.intuit.craft.streaming.avro.Message_dims.Builder();
  }

  /**
   * Creates a new Message_dims RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Message_dims RecordBuilder
   */
  public static com.intuit.craft.streaming.avro.Message_dims.Builder newBuilder(com.intuit.craft.streaming.avro.Message_dims.Builder other) {
    return new com.intuit.craft.streaming.avro.Message_dims.Builder(other);
  }

  /**
   * Creates a new Message_dims RecordBuilder by copying an existing Message_dims instance.
   * @param other The existing instance to copy.
   * @return A new Message_dims RecordBuilder
   */
  public static com.intuit.craft.streaming.avro.Message_dims.Builder newBuilder(com.intuit.craft.streaming.avro.Message_dims other) {
    return new com.intuit.craft.streaming.avro.Message_dims.Builder(other);
  }

  /**
   * RecordBuilder for Message_dims instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Message_dims>
    implements org.apache.avro.data.RecordBuilder<Message_dims> {

    /** Channel from where the event has been generated. */
    private java.lang.CharSequence channel;
    /** The Intuit item for which the event has been generated. */
    private java.lang.CharSequence item;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.intuit.craft.streaming.avro.Message_dims.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.channel)) {
        this.channel = data().deepCopy(fields()[0].schema(), other.channel);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.item)) {
        this.item = data().deepCopy(fields()[1].schema(), other.item);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Message_dims instance
     * @param other The existing instance to copy.
     */
    private Builder(com.intuit.craft.streaming.avro.Message_dims other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.channel)) {
        this.channel = data().deepCopy(fields()[0].schema(), other.channel);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.item)) {
        this.item = data().deepCopy(fields()[1].schema(), other.item);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'channel' field.
      * Channel from where the event has been generated.
      * @return The value.
      */
    public java.lang.CharSequence getChannel() {
      return channel;
    }

    /**
      * Sets the value of the 'channel' field.
      * Channel from where the event has been generated.
      * @param value The value of 'channel'.
      * @return This builder.
      */
    public com.intuit.craft.streaming.avro.Message_dims.Builder setChannel(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.channel = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'channel' field has been set.
      * Channel from where the event has been generated.
      * @return True if the 'channel' field has been set, false otherwise.
      */
    public boolean hasChannel() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'channel' field.
      * Channel from where the event has been generated.
      * @return This builder.
      */
    public com.intuit.craft.streaming.avro.Message_dims.Builder clearChannel() {
      channel = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'item' field.
      * The Intuit item for which the event has been generated.
      * @return The value.
      */
    public java.lang.CharSequence getItem() {
      return item;
    }

    /**
      * Sets the value of the 'item' field.
      * The Intuit item for which the event has been generated.
      * @param value The value of 'item'.
      * @return This builder.
      */
    public com.intuit.craft.streaming.avro.Message_dims.Builder setItem(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.item = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'item' field has been set.
      * The Intuit item for which the event has been generated.
      * @return True if the 'item' field has been set, false otherwise.
      */
    public boolean hasItem() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'item' field.
      * The Intuit item for which the event has been generated.
      * @return This builder.
      */
    public com.intuit.craft.streaming.avro.Message_dims.Builder clearItem() {
      item = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Message_dims build() {
      try {
        Message_dims record = new Message_dims();
        record.channel = fieldSetFlags()[0] ? this.channel : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.item = fieldSetFlags()[1] ? this.item : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
